{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "devflowfix-chart.fullname" . | replace "-dashboard" "" }}-gateway
  labels:
    {{- include "devflowfix-chart.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- with .hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      {{- with .tls }}
      tls:
        mode: {{ .mode }}
        certificateRefs:
          {{- toYaml .certificateRefs | nindent 10 }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
