{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "devflowfix-chart.fullname" . }}
  labels:
    {{- include "devflowfix-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "devflowfix-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from kgateway proxy (Gateway API)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway-name: {{ include "devflowfix-chart.fullname" . | replace "-dashboard" "" }}-gateway
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS for external APIs (Zitadel, Google Analytics, etc.)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
{{- end }}
